all: a3-ece650 rgen a2-ece650
	
a3-ece650: a3-ece650.c
	gcc a3-ece650.c -o a3-ece650
a2-ece650: a2-ece650.c
	gcc a2-ece650.c -o a2-ece650
rgen: rgen.c
	gcc rgen.c -o rgen
clean:
	rm -rf core a.out a3-ece650 rgen a2-ece650